title: "CFAD: Context-First Agentic Development"
description: "A comprehensive methodology for building production-ready applications with AI agents in Augment Code"
url: "https://tebiiee.github.io"
baseurl: "/cfad-augment-method"
theme: minima
